name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hetu_script: ^0.4.2+1
  hetu_std:
    git:
      url: https://github.com/hetu-community/hetu_std.git
      ref: main
  hetu_otp_util:
    git:
      url: https://github.com/hetu-community/hetu_otp_util.git
      ref: main
  hetu_spotube_plugin:
    git:
      url: https://github.com/KRTirtho/hetu_spotube_plugin.git
      ref: main
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  desktop_webview_window:
    git:
      path: packages/desktop_webview_window
      ref: feat/cookies
      url: https://github.com/KRTirtho/flutter-plugins.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/hetu_std/assets/bytecode/std.out
    - packages/hetu_spotube_plugin/assets/bytecode/spotube_plugin.out
    - assets/bytecode/plugin.out