name: Plugin Build
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version (x.x.x)'
        required: true
        default: 'continuous'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.2

      - name: Install dependencies
        run: dart pub global activate hetu_script_dev_tools
      
      - name: Run build
        run: make

      - name: Archive plugin
        run: make archive
        shell: bash
      
      - name: Upload plugin archive
        uses: actions/upload-artifact@v4
        with:
          path: build/plugin.smplug

      - name: Upload to release (${{ github.event.inputs.version }})
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: build/plugin.smplug
      